### ISSUE TITLE
Italic text wrapping issue

### ISSUE THREAD

**Issue by Blaziken257** [Medabots/medarot3#225] opened 2024-01-15 06:46 UTC
### Summary

There is at least one italic text string (with a dialogue with Viridiana) that has wrapping issues: an exclamation mark wraps around and spans two lines.

The original text (according to the spreadsheet in Section 20 on line 114) says this:

> Heeey, heeey. Over here, _meow!_

A save is attached to this issue (as a ZIP file).

To test this easily (once this is fixed -- might be necessary if the custom text preview doesn't catch this bug):

1. Use the debug mode (set `C480-C481` to `31 00`, then select the text debug (14th option from the top).
2. Set BANK (`C742`) to `0B`.
3. Set NOH (`C473`) to `00`.
4. Set NOL (`C474`) to `73`, then press A.

![M3 Italic Issue 1](https://github.com/Medabots/medarot3/assets/2187686/b82bc025-7072-44a0-a510-824b9d0fc915)
[Medarot 3 - Kabuto Version (Japan) (EN 20240114).zip](https://github.com/Medabots/medarot3/files/13935681/Medarot.3.-.Kabuto.Version.Japan.EN.20240114.zip)

**Comment by VariantXYZ** [comment] 2024-01-15 06:49
> <@RL,Viridiana,01>Heeey, heeey. Over here, meow!

![Untitled](https://github.com/Medabots/medarot3/assets/3066132/a409794a-3cb7-4e11-abeb-b2127be4ca8e)

from the previewer

**Comment by VariantXYZ** [comment] 2024-01-15 06:56
I changed the line manually for now anyway, but it looks like the issue is that the italic (and possibly the other fonts) need to have their pixels recounted. Italic '!' and 'i' and some other letters are off by one pixel on their actual width.

**Comment by VariantXYZ** [comment] 2024-01-15 19:27
@andwhyisit pointed out that it's actually just due to the way italics font work and how our auto-wrapping doesn't take into account that the italic font is designed to bleed into the normally 'ignored' spacing.

**Comment by VariantXYZ** [comment] 2024-01-17 02:30
Fixed by #226

**Closed by VariantXYZ** 2024-01-17 02:30 UTC
